#!/bin/bash
#
# Build RPM with docker
#
# Copyright (c) Jun Futagawa (jfut)
#
# This software is released under the 2-Clause BSD License.
# https://opensource.org/license/bsd-2-clause

set -euo pipefail

DOCKER_RPMBUILD_DIR="/pkg/rpmbuild"
SPEC_FILE_NAME="nginx-module-fancyindex.spec"

SCRIPT_DIR=$(dirname $(readlink -f $0))
HOST_RPMBUILD_DIR="${SCRIPT_DIR}/rpmbuild"

PACKAGER="$(basename "${0}")"

DEBUG="no"
PLATFORM=""

# Usage
usage() {
    cat << _EOF_
Usage:
    ${PACKAGER} [-d] [-h] [-p PLATFORM] BUILD_IMAGE_NAME:BUILD_IMAGE_TAG[:REPOSITORY][:MODULE_VERSION]

    Options:
        -d Debug mode.

    Build for RHEL/AlmaLinux/Rocky Linux 9 + AppStream module:
        ${PACKAGER} almalinux:9
        ${PACKAGER} almalinux:9:appstream:1.22
        ${PACKAGER} almalinux:9:appstream:1.24

    Build for RHEL/AlmaLinux/Rocky Linux 8 + AppStream module:
        # build almalinux:8 (version 1.14 is not supported)
        ${PACKAGER} almalinux:8:appstream:1.16
        ${PACKAGER} almalinux:8:appstream:1.18
        ${PACKAGER} almalinux:8:appstream:1.20
        ${PACKAGER} almalinux:8:appstream:1.22
        ${PACKAGER} almalinux:8:appstream:1.24

    Build for RHEL/AlmaLinux/Rocky Linux 8 + EPEL Stream module:
        # EPEL 8 Modularity was going away on February 15, 2023
        ${PACKAGER} almalinux:8:epel-modular:mainline

    Build for RHEL/AlmaLinux/Rocky Linux 9 linux/arm64/v8(aarch64) + AppStream module:
        ${PACKAGER} -p linux/arm64/v8 almalinux:9
        ${PACKAGER} -p linux/arm64/v8 almalinux:9:appstream:1.22
        ${PACKAGER} -p linux/arm64/v8 almalinux:9:appstream:1.24

_EOF_
}

setup_dir() {
    # Build directories
    for i in BUILD BUILDROOT RPMS SOURCES SPECS SRPMS tmp
    do
        DIR="${HOST_RPMBUILD_DIR}/${i}"
        if [[ ! -d "${DIR}" ]]; then
            mkdir "${DIR}"
        fi
    done
}

build() {
    local BUILD_ARGS="$1"

    local BUILD_IMAGE_NAME=$(echo ${BUILD_ARGS} | cut -d':' -f 1)
    local BUILD_IMAGE_TAG=$(echo ${BUILD_ARGS} | cut -d':' -f 2)
    local REPOSITORY=$(echo ${BUILD_ARGS} | cut -d':' -f 3)
    local MODULE_VERSION=$(echo ${BUILD_ARGS} | cut -d':' -f 4)

    local BUILD_IMAGE="${BUILD_IMAGE_NAME}:${BUILD_IMAGE_TAG}" 
    local BUILD_HOSTNAME="${BUILD_HOSTNAME:-${HOSTNAME}}"

    local DOCKER_OPTIONS=""
    local BUILD_CMD="$(dirname ${DOCKER_RPMBUILD_DIR})/build-rpm ${DOCKER_RPMBUILD_DIR} ${SPEC_FILE_NAME} ${REPOSITORY} ${MODULE_VERSION}"

    # Setup specificed platform
    if [[ ! -z "${PLATFORM}" ]]; then
        # Enable multiarch/qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        DOCKER_OPTIONS="--platform ${PLATFORM}"
    fi

    # Update build image
    docker pull ${DOCKER_OPTIONS} "${BUILD_IMAGE}"

    # Debug mode
    if [[ "${DEBUG}" = "yes" ]]; then
        echo
        echo "# Manual Build"
        echo "${BUILD_CMD}"
        echo
        DOCKER_OPTIONS="${DOCKER_OPTIONS} -it"
        BUILD_CMD="/bin/bash"
    fi

    # Build
    docker run \
        --name ${BUILD_HOSTNAME} \
        -h "${BUILD_HOSTNAME}" \
        -v "${SCRIPT_DIR}":$(dirname ${DOCKER_RPMBUILD_DIR}) \
        --rm=true \
        ${DOCKER_OPTIONS} \
        ${BUILD_IMAGE} \
        /bin/bash -c "${BUILD_CMD}"

    # Cleanup specificed platform
    if [[ ! -z "${PLATFORM}" ]]; then
        # Disable multiarch/qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p no
    fi
}

# Main
main() {
    [[ $# -lt 1 ]] && usage && exit 1

    while getopts dhp: OPT; do
        case "${OPT}" in
            "d" )
                DEBUG="yes" ;;
            "h" )
                usage
                exit 0
                ;;
            "p" )
                PLATFORM="${OPTARG}" ;;
            * )
                usage
                exit 1
                ;;
        esac
    done
    shift $((OPTIND - 1))

    build "${@}"
}

[[ ${#BASH_SOURCE[@]} = 1 ]] && main "${@:+$@}"
